version: "3.8"

services:
  mymongo:
    image: mongo:latest
    container_name: mymongo
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo_data:/data/db
    networks:
      - mynet

  api:
    image: mongo-api
    container_name: myapi
    restart: always
    ports:
      - "${API_PORT}:3000"
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mymongo:27017/${MONGO_DB_NAME}?authSource=admin
    depends_on:
      - mymongo
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
